DotnetAutheticationCookies/DotnetAutheticationCookies/Models/ErrorViewModel.cs
namespace DotnetAutheticationCookies.Models {
    public class ErrorViewModel {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty ( RequestId );
    }
}

DotnetAutheticationCookies/DotnetAutheticationCookies/Models/VMLogin.cs
namespace DotnetAutheticationCookies.Models {
    public class VMLogin {
        public string Email { get; set; }
        public string PassWord { get; set; }
        public bool KeepLoggedIn { get; set; }
    }
}

DotnetAutheticationCookies/DotnetAutheticationCookies/Controllers/AuthenticationController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using DotnetAutheticationCookies.Models;

namespace DotnetAutheticationCookies.Controllers {
    public class AuthenticationController : Controller {
        public IActionResult Login ( ) {
            ClaimsPrincipal claimUser = HttpContext.User;

            if ( claimUser.Identity.IsAuthenticated )
                return RedirectToAction ( "Index", "Home" );


            return View ();
        }

        [HttpPost]
        public async Task<IActionResult> Login ( VMLogin modelLogin ) {

            if ( modelLogin.Email == "user@example.com" &&
                modelLogin.PassWord == "123" )
            {
                List<Claim> claims = new List<Claim>() {
                    new Claim(ClaimTypes.NameIdentifier, modelLogin.Email),
                    new Claim("OtherProperties","Example Role")

                };

                ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims,
                    CookieAuthenticationDefaults.AuthenticationScheme );

                AuthenticationProperties properties = new AuthenticationProperties()
                {

                    AllowRefresh = true,
                    IsPersistent = modelLogin.KeepLoggedIn
                };

                await HttpContext.SignInAsync ( CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal ( claimsIdentity ), properties );

                return RedirectToAction ( "Index", "Home" );
            }

            ViewData ["ValidateMessage"] = "user not found";
            return View ();
        }
    }
}

DotnetAutheticationCookies/DotnetAutheticationCookies/Controllers/HomeController.cs
using DotnetAutheticationCookies.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Security.Claims;

namespace DotnetAutheticationCookies.Controllers {
    [Authorize]
    public class HomeController : Controller {
        private readonly ILogger<HomeController> _logger;

        public HomeController ( ILogger<HomeController> logger ) {
            _logger = logger;
        }

        public IActionResult Index ( ) {
            ClaimsPrincipal claimUser = HttpContext.User;

            return View ();
        }

        public async Task<IActionResult> LogOut ( ) {
            await HttpContext.SignOutAsync ( CookieAuthenticationDefaults.AuthenticationScheme );
            return RedirectToAction ( "Login", "Access" );
        }

        [ResponseCache ( Duration = 0, Location = ResponseCacheLocation.None, NoStore = true )]
        public IActionResult Error ( ) {
            return View ( new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier } );
        }
    }
}

DotnetAutheticationCookies/DotnetAutheticationCookies/Views/Authentication/Login.cshtml
@model DotnetAutheticationCookies.Models.VMLogin;
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
</head>
<body>
    <form asp-controller="Authentication" asp-action="Login" method="post">
        <h1>Login</h1>
        <input type="email" placeholder="Email" asp-for="Email" />
        <input type="password" placeholder="PassWord" asp-for="PassWord" />

        <label>
            <input type="checkbox" asp-for="KeepLoggedIn" />
            Keep me logged In.
        </label>
        <button type="submit">Login</button>

        @if ( ViewData ["ValidateMessage"] != null ) {
            <br />
            <br />
            <label>@ViewData ["ValidateMessage"]</label>
        }

    </form>
</body>
</html>

DotnetAutheticationCookies/DotnetAutheticationCookies/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DotnetAutheticationCookies/DotnetAutheticationCookies/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DotnetAutheticationCookies</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DotnetAutheticationCookies.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DotnetAutheticationCookies</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DotnetAutheticationCookies - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>